# Generated by Django 6.0.1 on 2026-02-02 07:51

import annoying.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaGiamGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('ten_chuong_trinh', models.CharField(max_length=200, verbose_name='Tên chương trình')),
                ('loai_giam', models.CharField(choices=[('percent', 'Giảm phần trăm'), ('fixed', 'Giảm cố định'), ('freeship', 'Miễn phí ship')], max_length=20, verbose_name='Loại giảm giá')),
                ('gia_tri_giam', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá trị giảm')),
                ('gia_tri_don_toi_thieu', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá trị đơn tối thiểu')),
                ('giam_toi_da', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giảm tối đa (với %)')),
                ('ngay_bat_dau', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('ngay_ket_thuc', models.DateTimeField(verbose_name='Ngày kết thúc')),
                ('so_luong', models.IntegerField(verbose_name='Số lượng mã')),
                ('da_su_dung', models.IntegerField(default=0, verbose_name='Đã sử dụng')),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mã giảm giá',
                'verbose_name_plural': 'Mã giảm giá',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
                ('ho_ten', models.CharField(blank=True, max_length=200, verbose_name='Họ tên')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('anh_dai_dien', models.ImageField(default='avatar/default avatar.jpg', upload_to='avatar', verbose_name='Ảnh đại diện')),
                ('trang_thai', models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Tạm khóa'), ('banned', 'Đã cấm')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Hồ sơ người dùng',
                'verbose_name_plural': 'Hồ sơ người dùng',
            },
        ),
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_danh_muc', models.CharField(max_length=200, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả')),
                ('anh_danh_muc', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Ảnh danh mục')),
                ('hien_thi', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('noi_bat', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('thu_tu', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('danh_muc_cha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='danh_muc_con', to='store.danhmuc', verbose_name='Danh mục cha')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ['thu_tu', 'ten_danh_muc'],
            },
        ),
        migrations.CreateModel(
            name='DiaChi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nguoi_nhan', models.CharField(max_length=200, verbose_name='Tên người nhận')),
                ('so_dien_thoai', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('dia_chi_chi_tiet', models.TextField(verbose_name='Địa chỉ chi tiết')),
                ('tinh_thanh', models.CharField(max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('quan_huyen', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('phuong_xa', models.CharField(max_length=100, verbose_name='Phường/Xã')),
                ('mac_dinh', models.BooleanField(default=False, verbose_name='Địa chỉ mặc định')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dia_chi_list', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Địa chỉ',
                'verbose_name_plural': 'Địa chỉ',
                'ordering': ['-mac_dinh', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_don_hang', models.CharField(max_length=50, unique=True, verbose_name='Mã đơn hàng')),
                ('tong_tien', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng tiền')),
                ('tien_giam', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tiền giảm')),
                ('phi_ship', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Phí ship')),
                ('phuong_thuc_thanh_toan', models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('vnpay', 'VNPay'), ('momo', 'MoMo'), ('zalopay', 'ZaloPay'), ('bank_transfer', 'Chuyển khoản ngân hàng')], default='cod', max_length=30, verbose_name='Phương thức thanh toán')),
                ('trang_thai_thanh_toan', models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('refunded', 'Đã hoàn tiền')], default='unpaid', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('trang_thai_don_hang', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('preparing', 'Đang chuẩn bị hàng'), ('shipping', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('cancelled', 'Đã hủy'), ('returned', 'Đã trả hàng')], default='pending', max_length=30, verbose_name='Trạng thái đơn hàng')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('ngay_dat', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('dia_chi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.diachi', verbose_name='Địa chỉ giao hàng')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='don_hang_list', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-ngay_dat'],
            },
        ),
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gio_hang', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Giỏ hàng',
                'verbose_name_plural': 'Giỏ hàng',
            },
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_hoa_don', models.CharField(max_length=50, unique=True, verbose_name='Mã hóa đơn')),
                ('tong_tien', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng tiền')),
                ('ngay_xuat', models.DateTimeField(auto_now_add=True, verbose_name='Ngày xuất')),
                ('don_hang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hoa_don', to='store.donhang', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Hóa đơn',
                'verbose_name_plural': 'Hóa đơn',
                'ordering': ['-ngay_xuat'],
            },
        ),
        migrations.CreateModel(
            name='DonHang_MaGiamGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_tien_giam', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền giảm')),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ma_giam_gia_ap_dung', to='store.donhang', verbose_name='Đơn hàng')),
                ('ma_giam_gia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.magiamgia', verbose_name='Mã giảm giá')),
            ],
            options={
                'verbose_name': 'Mã giảm giá đơn hàng',
                'verbose_name_plural': 'Mã giảm giá đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san_pham', models.CharField(max_length=300, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(max_length=320, unique=True, verbose_name='Slug')),
                ('ma_san_pham', models.CharField(max_length=100, unique=True, verbose_name='Mã sản phẩm (SKU)')),
                ('mo_ta', models.TextField(verbose_name='Mô tả')),
                ('mo_ta_chi_tiet', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('gia', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá gốc')),
                ('gia_khuyen_mai', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá khuyến mãi')),
                ('so_luong_ton', models.IntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('so_luong_canh_bao', models.IntegerField(default=10, verbose_name='Cảnh báo hết hàng')),
                ('noi_bat', models.BooleanField(default=False, verbose_name='Sản phẩm nổi bật')),
                ('luot_xem', models.IntegerField(default=0, verbose_name='Lượt xem')),
                ('da_ban', models.IntegerField(default=0, verbose_name='Đã bán')),
                ('trang_thai', models.CharField(choices=[('active', 'Đang bán'), ('out_of_stock', 'Hết hàng'), ('inactive', 'Ngừng bán')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('danh_muc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='san_pham_list', to='store.danhmuc', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='LichSuKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_thay_doi', models.IntegerField(verbose_name='Số lượng thay đổi (+/-)')),
                ('so_luong_truoc', models.IntegerField(verbose_name='Số lượng trước')),
                ('so_luong_sau', models.IntegerField(verbose_name='Số lượng sau')),
                ('ly_do', models.CharField(choices=[('import', 'Nhập hàng'), ('sold', 'Đã bán'), ('returned', 'Trả hàng'), ('damaged', 'Hàng hỏng'), ('adjustment', 'Điều chỉnh')], max_length=50, verbose_name='Lý do')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('nguoi_thuc_hien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_kho', to='store.sanpham', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Lịch sử kho',
                'verbose_name_plural': 'Lịch sử kho',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='DaXemGanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_xem', models.DateTimeField(auto_now=True, verbose_name='Thời gian xem')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_xem', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_xem', to='store.sanpham', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Đã xem gần đây',
                'verbose_name_plural': 'Đã xem gần đây',
                'ordering': ['-thoi_gian_xem'],
            },
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_sao', models.IntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], verbose_name='Số sao')),
                ('binh_luan', models.TextField(blank=True, verbose_name='Bình luận')),
                ('anh_danh_gia', models.ImageField(blank=True, null=True, upload_to='reviews', verbose_name='Ảnh đánh giá')),
                ('huu_ich', models.IntegerField(default=0, verbose_name='Số người thấy hữu ích')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_list', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_list', to='store.sanpham', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietGioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('gia', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá tại thời điểm thêm')),
                ('ngay_them', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm')),
                ('gio_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='store.giohang', verbose_name='Giỏ hàng')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sanpham', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Chi tiết giỏ hàng',
                'verbose_name_plural': 'Chi tiết giỏ hàng',
            },
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san_pham', models.CharField(max_length=300, verbose_name='Tên sản phẩm')),
                ('so_luong', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('gia', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá')),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='store.donhang', verbose_name='Đơn hàng')),
                ('san_pham', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.sanpham', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='AnhSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duong_dan_anh', models.ImageField(upload_to='product', verbose_name='Hình ảnh')),
                ('anh_chinh', models.BooleanField(default=False, verbose_name='Ảnh chính')),
                ('thu_tu', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anh_list', to='store.sanpham', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Ảnh sản phẩm',
                'verbose_name_plural': 'Ảnh sản phẩm',
                'ordering': ['-anh_chinh', 'thu_tu'],
            },
        ),
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cong_thanh_toan', models.CharField(choices=[('vnpay', 'VNPay'), ('momo', 'MoMo'), ('zalopay', 'ZaloPay'), ('bank_transfer', 'Chuyển khoản'), ('cod', 'COD')], max_length=50, verbose_name='Cổng thanh toán')),
                ('ma_giao_dich', models.CharField(max_length=200, verbose_name='Mã giao dịch')),
                ('so_tien', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền')),
                ('trang_thai', models.CharField(choices=[('pending', 'Đang xử lý'), ('success', 'Thành công'), ('failed', 'Thất bại'), ('cancelled', 'Đã hủy')], max_length=20, verbose_name='Trạng thái')),
                ('noi_dung', models.TextField(blank=True, verbose_name='Nội dung')),
                ('ngay_thanh_toan', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thanh toán')),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_thanh_toan', to='store.donhang', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'ordering': ['-ngay_thanh_toan'],
            },
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_thong_bao', models.CharField(choices=[('order', 'Đơn hàng'), ('promotion', 'Khuyến mãi'), ('system', 'Hệ thống'), ('review', 'Đánh giá')], default='system', max_length=30, verbose_name='Loại thông báo')),
                ('tieu_de', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('noi_dung', models.TextField(verbose_name='Nội dung')),
                ('lien_ket', models.CharField(blank=True, max_length=500, verbose_name='Liên kết')),
                ('da_doc', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_bao_list', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='TroChuyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai', models.CharField(choices=[('active', 'Đang chat'), ('closed', 'Đã đóng'), ('waiting', 'Chờ phản hồi')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tro_chuyen_khach', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
                ('quan_tri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tro_chuyen_admin', to=settings.AUTH_USER_MODEL, verbose_name='Quản trị viên')),
            ],
            options={
                'verbose_name': 'Trò chuyện',
                'verbose_name_plural': 'Trò chuyện',
                'ordering': ['-ngay_cap_nhat'],
            },
        ),
        migrations.CreateModel(
            name='TinNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField(verbose_name='Nội dung')),
                ('anh_dinh_kem', models.ImageField(blank=True, null=True, upload_to='chat', verbose_name='Ảnh đính kèm')),
                ('da_doc', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('thoi_gian_gui', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi')),
                ('nguoi_gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người gửi')),
                ('tro_chuyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan_list', to='store.trochuyen', verbose_name='Trò chuyện')),
            ],
            options={
                'verbose_name': 'Tin nhắn',
                'verbose_name_plural': 'Tin nhắn',
                'ordering': ['thoi_gian_gui'],
            },
        ),
        migrations.CreateModel(
            name='YeuThich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yeu_thich_list', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yeu_thich_list', to='store.sanpham', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Yêu thích',
                'verbose_name_plural': 'Yêu thích',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.AddIndex(
            model_name='donhang',
            index=models.Index(fields=['ma_don_hang'], name='store_donha_ma_don__f8ce38_idx'),
        ),
        migrations.AddIndex(
            model_name='donhang',
            index=models.Index(fields=['-ngay_dat'], name='store_donha_ngay_da_3d5460_idx'),
        ),
        migrations.AddIndex(
            model_name='sanpham',
            index=models.Index(fields=['slug'], name='store_sanph_slug_56db38_idx'),
        ),
        migrations.AddIndex(
            model_name='sanpham',
            index=models.Index(fields=['ma_san_pham'], name='store_sanph_ma_san__07f745_idx'),
        ),
        migrations.AddIndex(
            model_name='sanpham',
            index=models.Index(fields=['-luot_xem'], name='store_sanph_luot_xe_4f74a3_idx'),
        ),
        migrations.AddIndex(
            model_name='sanpham',
            index=models.Index(fields=['-da_ban'], name='store_sanph_da_ban_affd6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='daxemganday',
            unique_together={('nguoi_dung', 'san_pham')},
        ),
        migrations.AlterUniqueTogether(
            name='danhgia',
            unique_together={('nguoi_dung', 'san_pham')},
        ),
        migrations.AlterUniqueTogether(
            name='chitietgiohang',
            unique_together={('gio_hang', 'san_pham')},
        ),
        migrations.AlterUniqueTogether(
            name='yeuthich',
            unique_together={('nguoi_dung', 'san_pham')},
        ),
    ]
