# Generated by Django 6.0.1 on 2026-02-02 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaoCaoDoanThu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField(unique=True, verbose_name='Ngày')),
                ('so_don_hang', models.IntegerField(default=0, verbose_name='Số đơn hàng')),
                ('doanh_thu', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Doanh thu')),
                ('tien_giam', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tiền giảm giá')),
                ('phi_ship', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Phí ship')),
                ('gia_tri_trung_binh', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá trị đơn hàng TB')),
                ('so_khach_hang', models.IntegerField(default=0, verbose_name='Số khách hàng')),
                ('so_san_pham_ban', models.IntegerField(default=0, verbose_name='Số sản phẩm bán')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Báo cáo doanh thu',
                'verbose_name_plural': 'Báo cáo doanh thu',
                'ordering': ['-ngay'],
                'indexes': [models.Index(fields=['ngay'], name='store_baoca_ngay_e03a70_idx'), models.Index(fields=['-ngay', '-doanh_thu'], name='store_baoca_ngay_ccebac_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhanKhucKhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recency_score', models.IntegerField(default=1, help_text='1-5: Số ngày từ lần mua cuối (5 = mua gần nhất)', verbose_name='Điểm Recency')),
                ('frequency_score', models.IntegerField(default=1, help_text='1-5: Số lần mua hàng (5 = mua nhiều nhất)', verbose_name='Điểm Frequency')),
                ('monetary_score', models.IntegerField(default=1, help_text='1-5: Tổng chi tiêu (5 = chi nhiều nhất)', verbose_name='Điểm Monetary')),
                ('ngay_mua_cuoi', models.DateField(blank=True, null=True, verbose_name='Ngày mua cuối')),
                ('so_ngay_khong_mua', models.IntegerField(default=0, verbose_name='Số ngày không mua')),
                ('tong_so_don_hang', models.IntegerField(default=0, verbose_name='Tổng số đơn hàng')),
                ('tong_chi_tieu', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng chi tiêu')),
                ('gia_tri_don_hang_tb', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá trị đơn hàng TB')),
                ('segment', models.CharField(choices=[('vip', 'VIP - Khách hàng VIP'), ('loyal', 'Loyal - Trung thành'), ('at_risk', 'At Risk - Nguy cơ rời bỏ'), ('lost', 'Lost - Đã mất'), ('new', 'New - Khách mới'), ('regular', 'Regular - Thường xuyên'), ('promising', 'Promising - Tiềm năng'), ('need_attention', 'Need Attention - Cần chăm sóc')], default='new', max_length=20, verbose_name='Phân khúc')),
                ('rfm_score', models.CharField(default='111', help_text='VD: 555 = R5F5M5', max_length=3, verbose_name='RFM Score')),
                ('lan_cuoi_tinh', models.DateTimeField(auto_now=True, verbose_name='Lần cuối tính')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phan_khuc', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Phân khúc khách hàng',
                'verbose_name_plural': 'Phân khúc khách hàng',
                'ordering': ['-monetary_score', '-frequency_score', '-recency_score'],
                'indexes': [models.Index(fields=['segment'], name='store_phank_segment_5f796c_idx'), models.Index(fields=['-monetary_score', '-frequency_score'], name='store_phank_monetar_304d41_idx'), models.Index(fields=['ngay_mua_cuoi'], name='store_phank_ngay_mu_73f40f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThongKeVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.DateField(verbose_name='Tháng thống kê')),
                ('so_don_su_dung', models.IntegerField(default=0, verbose_name='Số đơn sử dụng')),
                ('tong_giam', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng tiền giảm')),
                ('tong_doanh_thu', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng doanh thu')),
                ('roi', models.DecimalField(decimal_places=2, default=0, help_text='ROI = (Doanh thu - Chi phí giảm giá) / Chi phí * 100', max_digits=8, verbose_name='ROI (%)')),
                ('gia_tri_don_hang_tb', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá trị đơn hàng TB')),
                ('ti_le_su_dung', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tỷ lệ sử dụng (%)')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('ma_giam_gia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_ke', to='store.magiamgia', verbose_name='Mã giảm giá')),
            ],
            options={
                'verbose_name': 'Thống kê voucher',
                'verbose_name_plural': 'Thống kê voucher',
                'ordering': ['-thang', '-tong_doanh_thu'],
                'indexes': [models.Index(fields=['thang'], name='store_thong_thang_ca174a_idx'), models.Index(fields=['ma_giam_gia', '-roi'], name='store_thong_ma_giam_d8bc71_idx')],
                'unique_together': {('ma_giam_gia', 'thang')},
            },
        ),
    ]
